platform :ios, '11.0'

target 'Leo_ios' do
 pod 'AppAuth', '>= 0.95.0'
 pod 'Firebase/Core'
 
 # Add the Firebase pod for Google Analytics
 pod 'Firebase/Analytics'

 # Add the pods for any other Firebase products you want to use in your app
 # For example, to use Firebase Authentication and Cloud Firestore
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
end
